# Generated by Django 3.1 on 2020-08-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee',
            new_name='client',
        ),
    ]
