# Generated by Django 3.0.9 on 2020-08-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.CharField(max_length=240)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logo/')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='brands/features/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icon/')),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='category/features/')),
                ('status', models.BooleanField(default=True)),
                ('show_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_limit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5)),
                ('purchase_limit_quantity', models.IntegerField(blank=True, null=True)),
                ('discounted', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_offer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5)),
                ('featured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5)),
                ('badge', models.CharField(blank=True, choices=[('sale', 'Sale'), ('hot', 'Hot'), ('limited', 'Limited')], max_length=10, null=True)),
                ('vat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=5)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='products.Brand')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='products.Category')),
            ],
        ),
    ]
